version: '3'

services:
  mongo:
    image: mongo:6.0.6-jammy
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_ADMIN_USERNAME: admin
      MONGO_INITDB_ADMIN_PASSWORD: admin
    volumes:
      - ./mongodb-init.js:/docker-entrypoint-initdb.d/mongodb-init.js:ro
    privileged: true
